INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP, CREATION_TIMESTAMP, UPDATE_TIMESTAMP)
VALUES(500, 'OTHER', 'EUR', 'Dmitri', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP, CREATION_TIMESTAMP, UPDATE_TIMESTAMP)
VALUES(100, 'GIFT', 'EUR', 'Dmitri', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP, CREATION_TIMESTAMP, UPDATE_TIMESTAMP)
VALUES(1700, 'SALARY', 'EUR', 'Dmitri', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null);

