INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(500, 'OTHER', 'EUR', 'Dmitri', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(100, 'GIFT', 'EUR', 'Dmitri', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(1700, 'SALARY', 'EUR', 'Dmitri', CURRENT_TIMESTAMP);

